name: 'xsmf-gpu'
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - snakemake=5.8.1
  - tensorflow-gpu=1.*
  - networkx
  - nose
  - xlrd
  - hyperopt
