configfile: 'data.yml'

from os.path import join

files = list(config.keys())
output_dir = 'output'
output_fmt = join(output_dir, '{filename}')

rule all:
    input:
        expand(output_fmt, filename=files)

rule download:
    output:
        output_fmt
    params:
        url = lambda w: config[w.filename]
    shell:
        '''
        wget -O {output} {params.url}
        '''
